<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><UseWPF>true</UseWPF><RevitApi>true</RevitApi><AssemblyName>SAUDICO.Federate.Revit2025</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="..\UI\UI.csproj"/><ProjectReference Include="..\Export\Export.csproj"/><ProjectReference Include="..\Core\Core.csproj"/><ProjectReference Include="..\Shared\Shared.csproj"/><ProjectReference Include="..\SAUDICO.Federate.Logging\SAUDICO.Federate.Logging.csproj"/></ItemGroup>  <ItemGroup>
    <Resource Include="Resources\*.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\config\apssettings.json" Link="config\apssettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="SAUDICO.Federate.Revit2025.addin" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <None Include="SAUDICO.Federate.Revit2025.addin" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
