<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><UseWPF>true</UseWPF><RevitApi>true</RevitApi><AssemblyName>SAUDICO.Federate.Revit2025</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="..\UI\UI.csproj"/><ProjectReference Include="..\Export\Export.csproj"/><ProjectReference Include="..\Core\Core.csproj"/><ProjectReference Include="..\Shared\Shared.csproj"/></ItemGroup></Project>