<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms><RequiresRevitApi>true</RequiresRevitApi></PropertyGroup><ItemGroup><ProjectReference Include="..\SAUDICO.Federate.Core\SAUDICO.Federate.Core.csproj"/><ProjectReference Include="..\SAUDICO.Federate.ACC\SAUDICO.Federate.ACC.csproj"/><ProjectReference Include="..\SAUDICO.Federate.Shared\SAUDICO.Federate.Shared.csproj"/></ItemGroup></Project>
